name: Build kernel
  
on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Do you want to create a gs201 release?'
        required: true
        type: boolean
        default: false

jobs:
  build-kernel-a15-gs201:
    uses: ./.github/workflows/build-kernel-a15-gs201.yml
    secrets: inherit
    
